#to define the configuration of the project
#instead of writing the configuration directly on the code, we can use  this configuration file

astra_db:
  collection_name: "flipkart_product_data"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 3

llm:
  provider: "google"
  model_name: "gemini-1.5-pro"  